feat : 친구 목록 API 구현 및 테스트 작성
Do-it-Together-DoTo/DoTo_Back pull request #150
Opened 2024-06-27 09:57 UTC by eyxnz

### PR Type

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [x] Other… Please describe: 테스트 작성

### 요약(Summary)
친구 목록 API 구현 및 테스트 작성

### Issue Number or Link

Resolves: #144

2024-06-27 11:29 UTC, jeongjiyeon315 approved these changes

2024-06-28 08:18 UTC, Cutaku requested changes

2024-06-28 08:18 UTC, Cutaku commented on src/main/java/site/doto/domain/member/repository/MemberRepositoryCustomImpl.java
> +                .orderBy(member.lastUpload.desc())
`lastUpload`가 사실상 중복될 일은 없긴 할텐데 그래도 명확하게 처리해주는게 좋을 것 같아요

2024-06-28 11:42 UTC, Cutaku approved these changes

2024-06-28 11:45 UTC, merged