feat :
Do-it-Together-DoTo/DoTo_Back pull request #34
Opened 2024-05-18 05:45 UTC by jeongjiyeon315

### PR Type

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [x] Other… Please describe: Test 코드 추가

### 요약(Summary)
- 회원 관련 Dto 생성
- 회원 관련 Test 코드 작성

### Issue Number or Link

Resolves: #33

2024-05-18 05:48 UTC, eyxnz approved these changes

2024-05-18 06:12 UTC, Cutaku requested changes

2024-05-18 06:12 UTC, Cutaku commented on src/main/java/site/doto/domain/member/controller/MemberController.java
> +    public ResponseDto<MemberDetailRes> memberDetail(
로그인 메서드 이름이 memberDetail 인게 좀 어색한 것 같습니다.

loginMemberDetails 나 loginDetails 정도로 수정하면 어떨까요?

2024-05-18 06:12 UTC, Cutaku commented on src/main/java/site/doto/domain/member/dto/MemberDetailRes.java
> +public class MemberDetailRes {
Details로 수정해주세요

2024-05-18 06:12 UTC, Cutaku commented on src/main/java/site/doto/domain/member/dto/PasswordFindReq.java
> +
`@NotNull` 필요할 것 같아요

2024-05-18 06:12 UTC, Cutaku commented on src/main/java/site/doto/domain/member/dto/PasswordModifyReq.java
> +    private String changePassword;
여기도 `@NotNull` 필요할 것 같아요

2024-05-18 06:12 UTC, Cutaku commented on src/test/java/site/doto/member/MemberControllerTest.java
> +                                )
Swagger에서 required 표기가 되는지 모르겠는데
된다면 각 필드 뒤에 `.optional()` 붙여주는게 좋을 것 같아요

2024-05-19 07:31 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/member/controller/MemberController.java
> +    public ResponseDto<MemberDetailRes> memberDetail(
넹 loginReq, loginRes가 더 깔끔한거같아서 이렇게 수정하겠습니다!

2024-05-19 07:31 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/member/dto/MemberDetailRes.java
> +public class MemberDetailRes {
수정했습니다!

2024-05-19 07:31 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/member/dto/PasswordModifyReq.java
> +    private String changePassword;
넹 추가했습니다!

2024-05-19 07:33 UTC, jeongjiyeon315 commented on src/test/java/site/doto/member/MemberControllerTest.java
> +                                )
swagger에 optional 필드표기가 안돼서 설명란에 Optional이라고 적어두겠습니다!

2024-05-19 11:21 UTC, Cutaku approved these changes

2024-05-20 01:11 UTC, merged