feat : Category Mock Api 구현 및 테스트 코드 작성 / 문서화
Do-it-Together-DoTo/DoTo_Back pull request #35
Opened 2024-05-18 07:46 UTC by Cutaku

### PR Type

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [x] Other… Please describe: 테스트 코드 작성 및 문서화

### 요약(Summary)
Category Mock Api 구현 및 테스트 코드 작성 / 문서화

### 상세 내용(Describe your changes)
 - 카테고리 엔티티의 color 타입을 enum으로 변경하고 color enum을 추가했습니다.
 - 카테고리 관련 mock API를 구현했습니다.
 - 카테과리 관련 API에 대한 테스트 코드를 작성하고 문서화 했습니다.

### Issue Number or Link

2024-05-19 11:25 UTC, eyxnz approved these changes

2024-05-20 12:05 UTC, jeongjiyeon315 requested changes

2024-05-20 12:05 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/category/dto/CategoryModifyReq.java
> +    public Category toEntity(Member member) {
수정하는 DTO에는toEntity 함수말고 entity에 수정 가능한 필드만 변경하는 함수를 만드는건 어떨까요??

2024-05-21 11:59 UTC, Cutaku commented on src/main/java/site/doto/domain/category/dto/CategoryModifyReq.java
> +    public Category toEntity(Member member) {
네 그게 더 깔끔할 것 같네요 수정했습니다

2024-05-21 12:56 UTC, jeongjiyeon315 approved these changes

2024-05-21 13:05 UTC, merged