feat : Todo Mock API 구현 및 테스트 코드 작성 / 문서화
Do-it-Together-DoTo/DoTo_Back pull request #37
Opened 2024-05-19 13:04 UTC by eyxnz

### PR Type

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [x] Other… Please describe: 테스트 코드 작성 및 문서화

### 요약(Summary)
Todo Mock API 구현 및 테스트 코드 작성 / 문서화

### 상세 내용(Describe your changes)
* Todo API 관련 DTO 추가
* Todo Mock API 구현
* Todo Test 작성 및 문서화

### Issue Number or Link

Resolves: #36

2024-05-20 12:17 UTC, jeongjiyeon315 requested changes

2024-05-20 12:17 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/todo/dto/TodoDetailsRes.java
> +    private boolean isDone;
wrapper class로 바꿔주세요!

2024-05-20 12:31 UTC, Cutaku requested changes

2024-05-20 12:31 UTC, Cutaku commented on src/main/java/site/doto/domain/todo/dto/TodoAddReq.java
> +}
1. 날짜는 서버에서 현재 시간으로 설정하면 돼서 프론트 측에서 받을 필요 없어 보입니다.
2. 지금은 당장은 필요 없긴 한데 toEntity() 메소드 추가해주세요
3. 여기 Id 포함해서 `@NotNull` 몇 개 빠져있는 게 있는데 추가해주세요.

2024-05-20 12:31 UTC, Cutaku commented on src/main/java/site/doto/domain/todo/dto/TodoListRes.java
> +@NoArgsConstructor
`@NoArgsConstructor` 이거 저도 Mock 데이터 만드느라 넣어놨는데 나중에 빼주세요

2024-05-20 12:31 UTC, Cutaku commented on src/main/java/site/doto/domain/todo/dto/TodoModifyReq.java
> +    @NotNull
여긴 `@NotNull`이 빠져야하지 않나요?

2024-05-20 12:31 UTC, Cutaku commented on src/test/java/site/doto/domain/todo/controller/TodoControllerTest.java
> +                                                        .description("Todo 변경 날짜")
여기 Swagger가 optional이 표기가 안돼서 
description 내용 뒤에 "Todo 변경 내용(Optional)" 이런 식으로 표기 해주는 게 좋을 것 같습니다

2024-05-20 12:31 UTC, Cutaku commented on src/main/java/site/doto/domain/todo/controller/TodoController.java
> +    ) {
여기 나머지 둘은 개행 없이 해서 맞추면 좋을거 같아요

2024-05-20 12:36 UTC, eyxnz commented on src/main/java/site/doto/domain/todo/dto/TodoDetailsRes.java
> +    private boolean isDone;
바꿨습니다!

2024-05-20 12:46 UTC, eyxnz commented on src/main/java/site/doto/domain/todo/dto/TodoModifyReq.java
> +    @NotNull
수정했습니다!

2024-05-20 12:53 UTC, eyxnz commented on src/main/java/site/doto/domain/todo/controller/TodoController.java
> +    ) {
수정했습니다~

2024-05-20 12:56 UTC, eyxnz commented on src/main/java/site/doto/domain/todo/dto/TodoAddReq.java
> +}
수정했습니다~

2024-05-21 12:02 UTC, Cutaku approved these changes

2024-05-21 12:56 UTC, jeongjiyeon315 approved these changes

2024-05-21 12:57 UTC, merged