feat : Friend Mock API 구현 및 테스트 코드 작성 / 문서화
Do-it-Together-DoTo/DoTo_Back pull request #39
Opened 2024-05-22 12:45 UTC by eyxnz

### PR Type

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [x] Other… Please describe: 테스트 코드 작성 및 문서화

### 요약(Summary)
Friend Mock API 구현 및 테스트 코드 작성 / 문서화

### 상세 내용(Describe your changes)
* 친구 상태 코드 Enum 생성
* 친구 API 관련 DTO 추가
* 친구 Mock API 구현
* 친구 Test 작성 및 문서화

### Issue Number or Link

Resolves: #38

2024-05-25 13:59 UTC, Cutaku requested changes

2024-05-25 13:59 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendDeclinedReq.java
> +    private Long toMemberId;
여기는 toMemberId보다 fromMemberId가 맞을 것 같아요

2024-05-25 13:59 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendDto.java
> +    }
![image](https://github.com/Do-it-Together-DoTo/DoTo_Back/assets/107826896/24c2850c-91e4-4f0e-bf1e-9b193f4a6d4e)
여기 화면에 필요한 데이터 같은데
fromMemberId, status는 필요 없을 것 같고 친구의 memberId, 대표캐릭터 정도 있으면 되지 않을까요?

2024-05-25 13:59 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendListReq.java
> +    private String lastFriendTodoDate;
무한 스크롤의 경우 첫 요청에서는 null이 들어와서 `NotNull` 빼는게 좋을거 같아요

2024-05-25 13:59 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendRequestReq.java
> +    }
친구 신청 요청은 어차피 status awating일거라 status는 받을 필요 없을 것 같아요
toEntity는 친구 신청 로직이 어떻게 될지 모르겠어서 필요할지 안할지 모르겠네요

2024-05-25 13:59 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendResponseReq.java
> +    private Long toMemberId;
여기도 fromMemberId가 좋을 것 같아요

2024-05-25 16:09 UTC, jeongjiyeon315 requested changes

2024-05-25 16:09 UTC, jeongjiyeon315 commented on src/main/java/site/doto/domain/friend/controller/FriendController.java
> +    public ResponseDto<?> friendRemove() {
`@PathVariable` 어노테이션이 있어야 toMemberId를 받아올 수 있어서 수정해주세요!

2024-06-01 13:54 UTC, Cutaku requested changes

2024-06-01 13:54 UTC, Cutaku commented on src/main/java/site/doto/domain/friend/dto/FriendDto.java
> +}
여기 닉네임도 필요하지 않을까요?

2024-06-01 13:54 UTC, Cutaku commented on src/main/java/site/doto/domain/member/dto/MembersSearchDto.java
> +}
![image](https://github.com/Do-it-Together-DoTo/DoTo_Back/assets/107826896/fa285f72-6eca-4487-b358-73bceceab574)
여기 프론트에서 친구 추가 / 차단 요청 보내려면 멤버id필요할 것 같아요
그리고 대표 캐릭터 사진도 필요할거 같아요

2024-06-01 13:57 UTC, Cutaku commented on src/main/java/site/doto/domain/member/controller/MemberController.java
> +        }
Mock 데이터니까 status 별로 데이터 하나씩은 있으면 좋을거 같아요

2024-06-08 15:57 UTC, jeongjiyeon315 approved these changes

2024-06-09 13:08 UTC, Cutaku approved these changes

2024-06-09 13:08 UTC, merged